### ISSUE TITLE
Cultures

### ISSUE THREAD

**Issue by MightNight** [ck2plus/CK2Plus_Rewrite#4] opened 2019-07-06 23:08 UTC
- See "projects" for milestone

**Comment by schwarherz** [comment] 2019-09-29 22:28
@daniloy I wasn't sure where you were with this so I just added checkmarks for two of the three steps. The third is being moved to another issue. Please check items off when they're done and, if the issue is complete, close it.

**Closed** 2019-10-03 15:42 UTC
Labels: enhancement
